# Generated by Django 3.0.8 on 2020-08-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.Bids'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
