# Generated by Django 3.0.8 on 2020-08-03 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200803_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.Listing'),
        ),
    ]
