# Generated by Django 3.0.8 on 2020-08-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200803_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='item',
        ),
    ]
