# Generated by Django 3.0.8 on 2020-08-04 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_bids_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='biditem', to='auctions.Listing'),
        ),
    ]
