# Generated by Django 3.0.8 on 2020-08-04 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200803_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.CurrentBid'),
        ),
    ]
