# Generated by Django 3.0.8 on 2020-08-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_listing_currentbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentbid',
            old_name='current_bid',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentbid',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.CurrentBid'),
        ),
    ]
