# Generated by Django 3.0.8 on 2020-08-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentbid',
            name='initial',
            field=models.BooleanField(default='True'),
        ),
    ]
